variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  
deploy:
  image: python:latest
  script:
  - pip install awscli
  - aws s3 cp public/* s3://plc.sites.mphtechinc.com/ --recursive
  - aws cloudfront create-invalidation --distribution-id $DISTRO_ID --paths "/*"
